---
framework: jest
preRun:
  command:
    - yarn install
    - yarn run build
preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "src/__tests__/*-test.js"
postMerge:
  env:
    NODE_ENV: test
  pattern:
    - "./src/stores/__tests__/FluxStore-test.js"
#     - "src/*/__tests__/*-test.js"
#     - "src/__tests__/*-test.js"
postRun:
  command:
    - yarn --version
version: 1.0
configFile: scripts/jest/environment.js
