---
framework: jest
preRun:
  command:
    - yarn install
    - yarn run build
    - mkdir  "/home/nucleus/repo/__tas"
    - touch "/home/nucleus/repo/__tas/discovery.json"
    - touch "/home/nucleus/repo/__tas/test_deps_map.json"
    - ls /home/nucleus/repo/__tas/
preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "src/__tests__/*-test.js"
postMerge:
  env:
    NODE_ENV: test
  pattern:
    - "./src/stores/__tests__/FluxStore-test.js"
#     - "src/*/__tests__/*-test.js"
#     - "src/__tests__/*-test.js"
postRun:
  command:
    - yarn --version
version: 1.0
configFile: jest.config.js
